//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject1.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class courts_visited
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Required!")]
        public string court_name { get; set; }
        [Required(ErrorMessage = "Required!")]
        public string address { get; set; }
        public Nullable<int> prisonerid { get; set; }
        [Required(ErrorMessage = "Required!")]
        public string visit_date { get; set; }
        [Required(ErrorMessage = "Required!")]
        public string description { get; set; }
    
        public virtual prisoner prisoner { get; set; }
    }
}
