//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject1.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class prisonerManagementSystemEntities : DbContext
    {
        public prisonerManagementSystemEntities()
            : base("name=prisonerManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<asset> asset { get; set; }
        public virtual DbSet<beneficiary> beneficiary { get; set; }
        public virtual DbSet<complaint> complaint { get; set; }
        public virtual DbSet<court_officer> court_officer { get; set; }
        public virtual DbSet<courts_visited> courts_visited { get; set; }
        public virtual DbSet<crime_record> crime_record { get; set; }
        public virtual DbSet<imprisonment_record> imprisonment_record { get; set; }
        public virtual DbSet<jail_officer> jail_officer { get; set; }
        public virtual DbSet<jailer> jailer { get; set; }
        public virtual DbSet<prisoner> prisoner { get; set; }
        public virtual DbSet<prisoner_transfer_request> prisoner_transfer_request { get; set; }
        public virtual DbSet<visitor> visitor { get; set; }
        public virtual DbSet<community_task> community_task { get; set; }
    }
}
