//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject1.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class prisoner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prisoner()
        {
            this.asset = new HashSet<asset>();
            this.beneficiary = new HashSet<beneficiary>();
            this.complaint = new HashSet<complaint>();
            this.courts_visited = new HashSet<courts_visited>();
            this.crime_record = new HashSet<crime_record>();
            this.imprisonment_record = new HashSet<imprisonment_record>();
            this.prisoner_transfer_request = new HashSet<prisoner_transfer_request>();
            this.visitor = new HashSet<visitor>();
            this.community_task = new HashSet<community_task>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "Required!")]
        public string name { get; set; }
        [Required(ErrorMessage = "Required!")]
        public string cnic { get; set; }
        [Required(ErrorMessage = "Required!")]
        public string dob { get; set; }
        [Required(ErrorMessage = "Required!")]
        public string father_name { get; set; }
        [Required(ErrorMessage = "Required!")]
        public string punishment { get; set; }
        [Required(ErrorMessage = "Required!")]
        [Range(1, 2, ErrorMessage = "Enter Category in Range!")]
        public int category { get; set; }
        [Required(ErrorMessage = "Required!")]
        public string imprisonment_duration { get; set; }
        [Required(ErrorMessage = "Required!")]
        [Range(1, 2, ErrorMessage = "Enter Cell Type in Range!")]
        public int cell_type { get; set; }
        [Required(ErrorMessage = "Required!")]
        public string allocated_meeting_time { get; set; }
        public string available_meeting_time { get; set; }
        [Required(ErrorMessage = "Required!")]
        public string address { get; set; }
        public string image { get; set; }
        public Nullable<int> stipend { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asset> asset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<beneficiary> beneficiary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<complaint> complaint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<courts_visited> courts_visited { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crime_record> crime_record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<imprisonment_record> imprisonment_record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prisoner_transfer_request> prisoner_transfer_request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visitor> visitor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<community_task> community_task { get; set; }
    }
}
