//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject1.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class prisoner_transfer_request
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Required!")]
        public string from_jail { get; set; }
        [Required(ErrorMessage = "Required!")]
        public string to_jail { get; set; }
        [Required(ErrorMessage = "Required!")]
        public string reason_of_transfer { get; set; }
        [Required(ErrorMessage = "Required!")]
        public string description { get; set; }
        public string request_date { get; set; }
        public string accept_date { get; set; }
        public string status { get; set; }
        public Nullable<int> prisonerid { get; set; }
        public Nullable<int> court_officer_id { get; set; }
        public Nullable<int> jailer_id { get; set; }
    
        public virtual court_officer court_officer { get; set; }
        public virtual jailer jailer { get; set; }
        public virtual prisoner prisoner { get; set; }
    }
}
