//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject1.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class visitor
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Required!")]
        public string name { get; set; }
        [Required(ErrorMessage = "Required!")]
        public string cnic { get; set; }
        [Required(ErrorMessage = "Required!")]
        public string contact { get; set; }
        [Required(ErrorMessage = "Required!")]
        public string address { get; set; }
        [Required(ErrorMessage = "Required!")]
        public string dob { get; set; }
        [Required(ErrorMessage = "Required!")]
        public string date_of_visit { get; set; }
        [Required(ErrorMessage = "Required!")]
        [Range(1, 100000, ErrorMessage = "Duration cannot be negative!")]
        public string duration { get; set; }
        public string image { get; set; }
        public Nullable<int> prisonerid { get; set; }
    
        public virtual prisoner prisoner { get; set; }
    }
}
